<a href="https://colab.research.google.com/github/nicolemartins7/Prova-Integrada_temp/blob/master/a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="Universidade Presbiteriana Mackenzie">
</head>

<img src="http://meusite.mackenzie.br/rogerio/mackenzie_logo/UPM.2_horizontal_vermelho.jpg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->


# **LAB SUB IA 2024S1**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

path = 'https://github.com/Rogerio-mack/IA_2024S1/raw/main/data/'

# Orientação para os Exercícios

Complete e execute o seu código aqui. Responda as questões no próprio corpo do notebook em formato `markdown`. Poste ao final seu notebook somente com **células 100% executáveis**.

# Case: **House Regions**






# Dados

In [ ]:
df = pd.read_csv(path + 'house_prices_sub.csv')
df.head()

Rooms Type      Price  Distance  Bedroom2  Bathroom  Car  Landsize  \
0      2    h  1035000.0       2.5       2.0       1.0  0.0     156.0   
1      3    h  1465000.0       2.5       3.0       2.0  0.0     134.0   
2      4    h  1600000.0       2.5       3.0       1.0  2.0     120.0   
3      3    h  1876000.0       2.5       4.0       2.0  0.0     245.0   
4      2    h  1636000.0       2.5       2.0       1.0  2.0     256.0   

   BuildingArea  YearBuilt             Regionname  
0          79.0     1900.0  Northern Metropolitan  
1         150.0     1900.0  Northern Metropolitan  
2         142.0     2014.0  Northern Metropolitan  
3         210.0     1910.0  Northern Metropolitan  
4         107.0     1890.0  Northern Metropolitan

# Novos casos

In [ ]:
cases = pd.read_csv(path + 'house_prices_sub_cases.csv')
cases.head()

Rooms Type     Price  Distance  Bedroom2  Bathroom  Car  Landsize  \
0      3    h  877294.0       9.0       3.0       1.0  2.0     445.0   
1      4    h  599040.0      33.0       3.0       2.0  2.0    2669.0   

   BuildingArea  YearBuilt  
0         128.0     1964.0  
1         165.0     1993.0

# Exercício 1. **Classification Model** (6,0)

 Faça um modelo de aprendizado de máquina de árvore de decisão para classificação de `Regionname`. Empregue 30% dos dados para teste, estratificados e `random_state=1` (na separação dos dados e no parâmetro da árvore de decisão). **Empregue como preditores somente variáveis numéricas**. Não é necessário normalizar os dados (pois empregamos árvores de decisão). Forneça as respostas sobre o seu modelo e faça a predição dos novos casos.

# Q1.

Qual a acuracidade obtida sobre o conjunto de teste?

Resposta: 0.75

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = df.drop(columns=['Regionname','Type'])
y = df['Regionname']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=1)

model = DecisionTreeClassifier(random_state=1)

model.fit(X_train, y_train)

print("Acurácia na base de teste:", model.score(X_test, y_test))

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))



Acurácia na base de teste: 0.7482203072311727
                            precision    recall  f1-score   support

      Eastern Metropolitan       0.59      0.59      0.59       295
          Eastern Victoria       0.59      0.67      0.62        15
     Northern Metropolitan       0.80      0.78      0.79       785
         Northern Victoria       0.50      0.53      0.51        19
South-Eastern Metropolitan       0.69      0.81      0.75       112
     Southern Metropolitan       0.79      0.82      0.80       812
      Western Metropolitan       0.73      0.69      0.71       618
          Western Victoria       0.64      0.69      0.67        13

                  accuracy                           0.75      2669
                 macro avg       0.67      0.70      0.68      2669
              weighted avg       0.75      0.75      0.75      2669



# Q2.

Qual a quantidade de Verdadeiros Positivos, Falso Positivos e Falsos Negativos para o valor de classe `Eastern Victoria`. Sugestão: veja a matriz de confusão.

Resposta: 10, 7, 5

In [ ]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

print(cm)


[[173   0  18   3  24  49  28   0]
 [  0  10   0   0   4   0   0   1]
 [ 24   0 614   2   2  60  83   0]
 [  0   1   4  10   2   0   0   2]
 [  9   1   5   3  91   2   0   1]
 [ 51   0  47   0   3 663  48   0]
 [ 34   4  77   1   5  69 427   1]
 [  0   1   0   1   1   0   1   9]]


In [ ]:
def get_confusion_matrix_elements(y_true, y_pred):
    """
    Retorna os valores de TN, FP, FN e TP para cada classe a partir de uma matriz de confusão.

    Parâmetros:
    y_true,  y_pred

    Retorna:
    dict: Um dicionário com TN, FP, FN, TP para cada classe.
    """
    cm = confusion_matrix(y_true, y_pred)
    num_classes = cm.shape[0]
    tn = {}
    fp = {}
    fn = {}
    tp = {}

    for i in range(num_classes):
        tp[i] = cm[i, i]
        fn[i] = np.sum(cm[i, :]) - cm[i, i]
        fp[i] = np.sum(cm[:, i]) - cm[i, i]
        tn[i] = np.sum(cm) - (tp[i] + fp[i] + fn[i])

    return {'TN': tn, 'FP': fp, 'FN': fn, 'TP': tp}

result = get_confusion_matrix_elements(y_test, y_pred)
print(result)


{'TN': {0: 2256, 1: 2647, 2: 1733, 3: 2640, 4: 2516, 5: 1677, 6: 1891, 7: 2651}, 'FP': {0: 118, 1: 7, 2: 151, 3: 10, 4: 41, 5: 180, 6: 160, 7: 5}, 'FN': {0: 122, 1: 5, 2: 171, 3: 9, 4: 21, 5: 149, 6: 191, 7: 4}, 'TP': {0: 173, 1: 10, 2: 614, 3: 10, 4: 91, 5: 663, 6: 427, 7: 9}}


In [ ]:
result['TP'][1], result['FP'][1], result['FN'][1]

(10, 7, 5)

# Q3.

Qual a predição dos novos casos?

Resposta: 'Southern Metropolitan' 'South-Eastern Metropolitan'

In [ ]:
y_pred = model.predict(cases.drop(columns='Type'))

print("Previsões para os novos casos:", y_pred)

Previsões para os novos casos: ['Southern Metropolitan' 'South-Eastern Metropolitan']


# Exercício 2. **Regression Model** (4,0)

 Faça um modelo de regressão linear com o pacote `statsmodels` para estimar o preço dos imóveis. **Empregue como preditores todas as variáveis**, exceto o preço.  Forneça as respostas sobre o seu modelo e faça a predição dos novos casos.

# Q3.

Qual o coeficiente de determinação obtido e quais coeficientes aparencem como não significativos na regressão estimada?
Sugestão: empregue a formula abaixo para estimar a regressão.

Resposta: 0.644, Regionname[T.Western Victoria] e Bedroom2

In [ ]:
formula = 'Price ~ Rooms + Type + Distance + Bedroom2 + Bathroom + Car + Landsize + BuildingArea + YearBuilt + Regionname'

In [ ]:
import statsmodels.formula.api as sm

X = df.drop(columns=['Price'])
y = df['Price']

model = sm.ols(formula=formula, data=df)
model = model.fit()

print(model.summary())




                            OLS Regression Results                            
Dep. Variable:                  Price   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.644
Method:                 Least Squares   F-statistic:                     946.0
Date:                Tue, 04 Jun 2024   Prob (F-statistic):               0.00
Time:                        13:51:17   Log-Likelihood:            -1.2747e+05
No. Observations:                8895   AIC:                         2.550e+05
Df Residuals:                    8877   BIC:                         2.551e+05
Df Model:                          17                                         
Covariance Type:            nonrobust                                         
                                               coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------

# Q5.

Assumindo que os novos casos são de 'Southern Metropolitan' (transformação já encontra-se abaixo), qual a previsão de preço dos dois novos casos?

Resposta:
USD 1416131.23 e
USD 801979.12


In [ ]:
cases['Regionname'] = 'Southern Metropolitan'

In [ ]:
y_pred = model.predict(cases.drop(columns='Price'))

print("Previsões dos preços para os novos casos:\n")

for value in y_pred:
  print(f"USD {value:.2f}")

Previsões dos preços para os novos casos:

USD 1416131.23
USD 801979.12
